###
GRAPHQL http://localhost:8080/graphql

query user($page: Int, $size: Int) {
    userList(page: $page, size: $size, sort: {orders:[{direction: ASC, property: "username"}]}) {
        username

        id
        updateTime
        __typename
    }
}

{
  "page": 1,
  "size": 10
}
###
