###
GRAPHQL http://localhost:8080/graphql

query user($page: Int, $size: Int) {
    userPage(pageInfo: {page: $page, size: $size, sort: ["username"]}) {
        content {
            id,
            username,
            email,
            admin,
            loginTime,
            createTime,
            updateTime
        }
        totalElement,
        __typename
    }
}

{
  "page": 1,
  "size": 10
}
###
