server:
  port: 8080
spring:
  profiles:
    active: mysql
  graphql:
    graphiql:
      enabled: true
persistence: jpa
# ======== JWT配置 ========
jwt:
  secret: 20240604
  expirationTime: 604800
  issuer: thatisme.cn
  header: Authorization
  tokenHead: Bearer