spring:
  datasource:
    driver-class-name: org.digitalforge.log4jdbc.LoggingDriver
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/blog_test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456