spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password: 
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true