### label 查询
GRAPHQL http://localhost:8080/graphql

query label {
    labelPage(query: {pageInfo: {page: 1, size: 10, sort: ["id"]}}) {
        content {
            ... on Label {
                id
                name
            }
        }
        totalElement,
        __typename
    }
}

{
  "page": 1,
  "size": 10
}


### label 新增、更新
GRAPHQL http://localhost:8080/graphql

mutation label {
    labelSaveOrUpdate(command: {id: "1", name: "label2"}) {
        id, name
    }
}

### label 删除
GRAPHQL http://localhost:8080/graphql

mutation label {
    labelDelete(ids: ["1"]) {
        totalElement
    }
}
