### login 登录
GRAPHQL http://localhost:8080/graphql

mutation login($username: String!, $password: String!) {
    login(command: {username: $username, password: $password}) {
        token
        username
        totp
    }
    __typename
}

{
  "username": "zhangsan",
  "password": "123456"
}

### login 登录 TOTP
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6aGFuZ3NhbiIsImlzcyI6InRoYXRpc21lLmNuIiwiYXVkIjoiVE9UUCIsImlhdCI6MTc0MTAwNTU4MywiZXhwIjoxNzQxMDA1ODgzfQ.w7khAJKd2P-aq6ltlWjX6FxabJd4pjzdSdxR_lbVkVk

mutation loginTotp($code: Int!) {
    loginTotp(command: {code: $code}) {
        token
        username
        totp
    }
    __typename
}

{
  "code": 927288
}

### login 登录 获取qr
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6aGFuZ3NhbiIsImlzcyI6InRoYXRpc21lLmNuIiwiYXVkIjoiVE9UUCIsImlhdCI6MTc0MTAwNDgzNywiZXhwIjoxNzQxMDA1MTM3fQ._PUaQ87HPjeSnmy6-RhgSTYwmm8RAPKZ5adMn91k7pg

query qrBase64 {
    qrBase64
}

### login 绑定 Totp
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6aGFuZ3NhbiIsImlzcyI6InRoYXRpc21lLmNuIiwiYXVkIjoiVE9UUCIsImlhdCI6MTc0MTAwNTE1OCwiZXhwIjoxNzQxMDA1NDU4fQ._Q_jrc3KSPP-uFaHJnZxQ0nTwIlShMEJZRv8mbQGCL0

mutation bindTotp {
    bindTotp
}

### 带token的请求
### user 查询
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImlzcyI6InNwcmluZ2Jvb3QzLXNlY3VyaXR5IiwiYXVkIjpudWxsLCJpYXQiOjE3MTMyMzY1MjEsImV4cCI6MTcxMzg0MTMyMX0.OqS1hxfVMU115-mHTy379cl3gcYla1BASo5juGibvjw

query user {
    userPage(query: {username: "", pageInfo: {page: 1, size: 10, sort: ["id"]}}) {
        content {
            ... on User {
                id,
                username,
                email,
                admin,
                loginTime,
                createTime,
                updateTime
            }
        }
        totalElement,
        __typename
    }
}

{
  "page": 1,
  "size": 10
}