### user 查询
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6aGFuZ3NhbiIsImlzcyI6InRoYXRpc21lLmNuIiwiYXVkIjpudWxsLCJpYXQiOjE3NDEwMDU2MzEsImV4cCI6MTc0MTAwOTIzMX0.ccT8vC2f9tbRLVrtz9mxiA0g7vV_aKGSDJ7keJ1BUf8

query user {
    userPage(query: {username: "", pageInfo: {page: 1, size: 10, sort: ["id"]}}) {
        content {
            ... on User {
                id,
                username,
                email,
                admin,
                loginTime,
                createTime,
                updateTime
            }
        }
        totalElement,
        __typename
    }
    userById(id: 1) {
        id,
        username,
        email,
        admin,
        loginTime,
        createTime,
        updateTime
    }
}

{
  "page": 1,
  "size": 10
}

### user 新增、更新
GRAPHQL http://localhost:8080/graphql

mutation user {
    userSaveOrUpdate(command: {username: "lisi", email: "lisi@q.cn"}) {
    id
    }
}

### user 删除
GRAPHQL http://localhost:8080/graphql

mutation user {
    userDelete(ids: [1730153406822633472]) {
    totalElement
    }
}
